baseURL = 'https://petrie.github.io/'
languageCode = 'zh-cn'
title = "Petrie's Site"
theme = "ananke"
disqusShortname = "petrie"
googleAnalytics = "G-T6WSQ8M692"
DefaultContentLanguage = "zh"
Paginate = 9

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    date_format = "2006年01月2日"
    body_classes = "baskerville bg-washed-yellow"
    recent_posts_number = 6
    cover_dimming_class = ""
    show_reading_time = true


[[params.ananke_socials]]
    name = "github"
    url = "https://github.com/petrie"

[permalinks]
    posts = '/:year/:month/:title/'

[menu]
    [[menu.main]]
        identifier = "categories"
        name = "分类"
        url = "/categories/"
        weight = 10

    [[menu.main]]
        identifier = "tags"
        name = "标签"
        url = "/tags/"
        weight = 20
