baseURL = 'https://petrie.github.io/'
languageCode = 'zh-cn'
title = "Petrie's Site"
theme = "ananke"
disqusShortname = "petrie"
googleAnalytics = "G-SZDN75YQDS"
DefaultContentLanguage = "zh"
Paginate = 9

[params]
    date_format = "2006年01月2日"
    recent_posts_number = 6
    cover_dimming_class = ""
    show_reading_time = true


[[params.ananke_socials]]
    name = "github"
    url = "https://github.com/petrie"

[permalinks]
    posts = '/:year/:month/:title/'

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'github'
    tabWidth = 4