baseURL = 'https://petrie.github.io/'
languageCode = 'zh-cn'
title = "Petrie's Site"
theme = "ananke"
disqusShortname = "petrie"
googleAnalytics = "G-SZDN75YQDS"
DefaultContentLanguage = "zh"
Paginate = 9

[params]
    date_format = "2006年01月2日"
    body_classes = "baskerville bg-washed-yellow"
    recent_posts_number = 6
    cover_dimming_class = ""
    show_reading_time = true


[[params.ananke_socials]]
    name = "github"
    url = "https://github.com/petrie"

[permalinks]
    posts = '/:year/:month/:title/'